### ISSUE TITLE
GUI: create race select and new race page

### ISSUE THREAD

**Issue by j-boss** [ifphobic/MeoRace#4]
GUI: create a page to select from active races and a separate page to create a new one
user goal: administrators can set up new races and select existing and active ones for detailed setup

list of active races, access to past (archived) races and to new race form

**Comment by ifphobic** [comment]
Sollte jetzt funktionieren. RaceSelect ueber UserEdit

e0650a92a08feb94b722688ee410e0412531f9ef

**Comment by j-boss** [comment]
ist race select an user gebunden? es wird doch hoffentlich unzählige anonymous user geben, die unabhängig das race wählen können...

ich schaus mir an (hoffentlich verstehe ich das in nützlicher frist)...

danke schonmal und grüsse,
jakob

**Comment by ifphobic** [comment]
Nicht angemeldete Benutzer bekommen jetzt ebenfalls eine Session.
In dieser Session ist die RaceId gespeichert.
Bei den angemeldeten Benutzer wird die RaceId wie bisher aus der User-Tabelle gelesen.

endlich done.
