### ISSUE TITLE
race select page

### ISSUE THREAD

**Issue by j-boss** [ifphobic/MeoRace#46]
eine seite zum auswählen des gewünschten rennens, falls mehrere gleichzeitig laufen:
- wenn man schon eins gewählt hat zum ändern über ein menu
- wenn man die seite zum ersten mal aufruft und noch keine session <> rennen verknüpfung besteht
- wenn man die seite über ein perma-link aufruft, aber doch ein anderes rennen wählen will (über menu wie bei punkt 1)

**Comment by j-boss** [comment]
see also #4 and #5

**Comment by ifphobic** [comment]
Bitte schaut euch die aktuelle Loesung mal an.
Brauchen wir das Menu noch?

a82250855a649e68946eecd51c2b53e274f9e8f5

**Comment by ifphobic** [comment]
done
