### ISSUE TITLE
auswahl des rennens über permalink

### ISSUE THREAD

**Issue by j-boss** [ifphobic/MeoRace#48]
via permalink die session direkt mit einem rennen aufrufen

**Comment by ifphobic** [comment]
Man kann jetzt ins Ranking eines Rennes springen mit login.php?raceId=xxx

Wenn wir Seiten mit sprechenden Namen wollen machen wir statische Seiten die auf login.php weiterleiten mit folgendem Inhalt:

<html><head><meta http-equiv='refresh' content='0; URL=login.php?raceId=XXX' /></head></html?
